export const projects = [
  // {
  //   title: 'Play To Earn',
  //   // description: "Creator",
  //     image: 'https://i.imgur.com/Msg51g7.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Polygon'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://play-to-earn.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'NFT Ticket Concert',
  //   // description: "Creator",
  //     image: 'https://i.imgur.com/QYh4TFY.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Polygon'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://app.unlock-protocol.com/checkout?id=9a41cb76-d3e5-484d-8466-49c94b9ead4d',
  //   id: 0,
  // },
  // {
  //   title: 'Staking Dapp',
  //   // description: "Creator",
  //     image: 'https://i.imgur.com/AB5E1pZ.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Polygon'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://skating-pablofelipe01.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Twitter Followers',
  //   // description: "Creator",
  //     image: 'https://i.imgur.com/4vkzprZ.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Polygon'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://app.unlock-protocol.com/checkout?id=95f9d978-efe6-4d5f-986b-0dadea047ce6',
  //   id: 0,
  // },
  // {
  //   title: 'Talent Plus',
  //   // description: "Creator",
  //     image: 'https://i.imgur.com/h0OKRAj.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Solana'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://talent-plus-ashen.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Agualinda',
  //   // description: "NoN Profit",
  //     image: 'https://i.imgur.com/qxPo8Tm.png',
  //     tags: ['Ts', 'Next', 'Vercel', 'Node', 'Solana'],
  //   // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
  //   source: 'https://camphillagualinda.com/token',
  //   id: 0,
  // },
  // {
  //   title: 'Reef Token',
  //   // description: "Environment Industry",
  //     image: 'https://i.imgur.com/kKSMt4I.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   // visit: 'https://github.com/pablofelipe01/reef-swap',
  //   source: 'https://reef-swap-form.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Sports Token',
  //   // description: "Sports Industry",
  //     image: 'https://i.imgur.com/8bMGbm3.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   // visit: 'https://github.com/pablofelipe01/xpo_token',
  //   source: 'https://xpo2-0.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Puerto Venus',
  //   // description: "Films Industry",
  //     image: 'https://i.imgur.com/DkP4r83.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   // visit: 'https://github.com/pablofelipe01/reef-swap',
  //   source: 'https://venus-2-0.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Azul Token',
  //   // description: "Marketing Industry",
  //     image: 'https://i.imgur.com/LT6jWdT.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   // visit: 'https://github.com/pablofelipe01/azul-swap-form',
  //   source: 'https://azul2-0.vercel.app/',
  //   id: 0,
  // },
  // {
  //   title: 'Si Senor',
  //   // description: "NFTs Market Place",
  //     image: 'https://i.imgur.com/Ca8HbWt.png',
  //     tags: ['Solidity', 'Next', 'Vercel', 'Node', 'Matic'],
  //   // visit: 'https://github.com/pablofelipe01/nft_marketplace',
  //   source: 'https://www.sisenor.io/',
  //   id: 0,
  // },
 
 
  {
    title: 'BTM',
    // description: "Creator",
      image: 'https://i.imgur.com/d8t6gCN.png',
      tags: [ 'Solana Network'],
    // visit: 'https://github.com/pablofelipe01/token-camphill-agualinda',
    source: 'https://tok-sol-governance-token.vercel.app/',
    id: 0,
  },
];

export const team = [
  {
    title: 'Investor',
    // description: "Sustainability",
      image: 'https://i.imgur.com/eYl39K0.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/angela-maria-acosta-a99687a1/',
    // visit: 'https://xpo-pied.vercel.app/',
    id: 0,
  },
  {
    title: 'Math Freak',
    // description: "Web 3 & Math",
      image: 'https://i.imgur.com/YxQQfUg.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/pablo-f-acebedo/',
    // visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
  {
    title: 'Serious Business Man',
    // description: "Media",
      image: 'https://i.imgur.com/SJmKW12.png',
      tags: ['Solidity', 'Next', 'Vercel', 'Node', 'Matic'],
    source: 'https://www.linkedin.com/in/jorge-morales-castillo-5264ab15a/',
    visit: 'https://si-senor-market.vercel.app/',
    id: 0,
  },
  {
    title: 'Advisor',
    // description: "Metaverse",
      image: 'https://i.imgur.com/fo8zY81.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/paolomiscia/',
    // visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
 
  // {
  //   title: 'Advisor',
  //   // description: "Media",
  //     image: 'https://i.imgur.com/usDVTPG.png',
  //     tags: ['Solidity', 'Next', 'Vercel', 'Node', 'Matic'],
  //   source: 'https://www.linkedin.com/in/camilo-zuluaga-45a068191/',
  //   visit: 'https://si-senor-market.vercel.app/',
  //   id: 0,
  // },
];
export const token = [
  // {
  //   title: 'Native Token',
  //   // description: "Click Buy Tok_Sol Token",
  //     image: 'https://i.imgur.com/uxR5RCe.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   source: 'https://toksol-token.vercel.app/',
  //   visit: 'https://toksol-token.vercel.app/',
  //   id: 0,
  // },
  {
    title: 'VC Token',
    // description: "Click Buy Tok_Sol Token",
      image: 'https://i.imgur.com/WaamJV6.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://tok-sol-governance-token.vercel.app/',
    visit: 'https://tok-sol-governance-token.vercel.app/',
    id: 0,
  }

]
export const nft = [
  // {
  //   title: 'Native Token',
  //   // description: "Click Buy Tok_Sol Token",
  //     image: 'https://i.imgur.com/uxR5RCe.png',
  //     tags: ['Solana', 'Next', 'Vercel', 'Node'],
  //   source: 'https://toksol-token.vercel.app/',
  //   visit: 'https://toksol-token.vercel.app/',
  //   id: 0,
  // },
  {
    title: 'NFT',
    // description: "Click Buy Tok_Sol Token",
      image: 'https://i.imgur.com/H0mY1JA.png',
      tags: ['Polygon', 'Next', 'Vercel', 'Node'],
    source: 'https://app.unlock-protocol.com/checkout?id=95f9d978-efe6-4d5f-986b-0dadea047ce6',
    mint: 'https://app.unlock-protocol.com/checkout?id=95f9d978-efe6-4d5f-986b-0dadea047ce6',
    id: 0,
  }

]

export const TimeLineData = [
  { year: 2017, text: 'New Blockchain was Born, In November of 2017, Anatoly Yakovenko published a whitepaper describing Proof of History, a technique for keeping time between computers that do not trust one another. ', },
  { year: 2018, text: 'On February 13th of 2018, Greg began prototyping the first open source implementation of Anatoly`s whitepaper. The project was published to GitHub under the name Silk in the loomprotocol organization.', },
  { year: 2019, text: ' July 19th, published a 50-node, permissioned, public testnet consistently supporting bursts of 250,000 transactions per second.', },
  { year: 2021, text: 'We Register the TS DAO in the Solana network with Vault hash: BeB.....tPd and the slogan: "Give someone a dollar, and they will help you for a day. Give them tokenized ownership, and they will be on your side for a lifetime."', },
  { year: 2022, text: 'June 2022 we publish the withe paper “Bidirectional Cryptographic Tokens” A bi-directional token is a price-sensing, self-liquidity-generating, self-custodial and self-regulating Smart Contract, deployed on a blockchain.', },
  { year: 2022, text: 'August 2022 we launch the first : bi-directional token is a price-sensing, self-liquidity-generating, self-custodial and self-regulating Smart Contract, deployed on a blockchain.', },
  { year: 2023, text: 'January 2023 we have fully working Bidirectional Cryptographic Tokens in 5 different industries', },
  { year: 2023, text: 'April 2023 We change the Name to BTM -Bidirectional Tokenization Model-, and develop full mobile functionality' },

  
];