export const projects = [
  {
    title: 'Reef Token',
    description: "Environment Industry",
      image: 'https://i.imgur.com/kKSMt4I.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://github.com/pablofelipe01/reef-swap',
    visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
  {
    title: 'Sports Token',
    description: "Sports Industry",
      image: 'https://i.imgur.com/8bMGbm3.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://github.com/pablofelipe01/xpo_token',
    visit: 'https://xpo-pied.vercel.app/',
    id: 0,
  },
  {
    title: 'Puerto Venus',
    description: "Films Industry",
      image: 'https://i.imgur.com/DkP4r83.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://github.com/pablofelipe01/reef-swap',
    visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
  {
    title: 'Azul Token',
    description: "Marketing Industry",
      image: 'https://i.imgur.com/LT6jWdT.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://github.com/pablofelipe01/azul-swap-form',
    visit: 'https://azul-kappa.vercel.app/',
    id: 0,
  },
  {
    title: 'Si Senor',
    description: "NFTs Market Place",
      image: 'https://i.imgur.com/eH3NcyS.png',
      tags: ['Solidity', 'Next', 'Vercel', 'Node', 'Matic'],
    source: 'https://github.com/pablofelipe01/nft_marketplace',
    visit: 'https://si-senor-market.vercel.app/',
    id: 0,
  },
];

export const team = [
  {
    title: 'Pablo',
    description: "Web 3 & Math",
      image: 'https://i.imgur.com/YxQQfUg.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/pablo-f-acebedo/',
    // visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
  {
    title: 'Angela',
    description: "Sustainability",
      image: 'https://i.imgur.com/eYl39K0.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/angela-maria-acosta-a99687a1/',
    // visit: 'https://xpo-pied.vercel.app/',
    id: 0,
  },
  {
    title: 'Paolo',
    description: "Metaverse",
      image: 'https://i.imgur.com/fo8zY81.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/paolomiscia/',
    // visit: 'https://reef-swap-form.vercel.app/',
    id: 0,
  },
  {
    title: 'Holger',
    description: "Financial",
      image: 'https://i.imgur.com/bViZrf2.png',
      tags: ['Solana', 'Next', 'Vercel', 'Node'],
    source: 'https://www.linkedin.com/in/holger-sandquist-92737834/',
    visit: 'https://azul-kappa.vercel.app/',
    id: 0,
  },
  {
    title: 'Camilo',
    description: "Media",
      image: 'https://i.imgur.com/D7HjgZ1.jpg',
      tags: ['Solidity', 'Next', 'Vercel', 'Node', 'Matic'],
    source: 'https://www.linkedin.com/in/camilo-zuluaga-45a068191/',
    visit: 'https://si-senor-market.vercel.app/',
    id: 0,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'New Blockchain was Born, In November of 2017, Anatoly Yakovenko published a whitepaper describing Proof of History, a technique for keeping time between computers that do not trust one another. ', },
  { year: 2018, text: 'On February 13th of 2018, Greg began prototyping the first open source implementation of Anatoly`s whitepaper. The project was published to GitHub under the name Silk in the loomprotocol organization.', },
  { year: 2019, text: ' July 19th, published a 50-node, permissioned, public testnet consistently supporting bursts of 250,000 transactions per second.', },
  { year: 2021, text: 'We Register the TS DAO in the Solana network with Vault hash: BeB6qDcgjEY9rHxy DAJS99cAuR3jszUeZU21 HqumCtPd and the slogan: "Give someone a dollar, and they will help you for a day. Give them tokenized ownership, and they will be on your side for a lifetime."', },
  { year: 2022, text: 'June 2022 we publish the withe paper “Bidirectional Cryptographic Tokens” A bi-directional token is a price-sensing, self-liquidity-generating, self-custodial and self-regulating Smart Contract, deployed on a blockchain.', },
  { year: 2022, text: 'August 2022 we launch the first : bi-directional token is a price-sensing, self-liquidity-generating, self-custodial and self-regulating Smart Contract, deployed on a blockchain.', },
  { year: 2023, text: 'January 2023 we have fully working Bidirectional Cryptographic Tokens in 5 different industries', },

  
];